import { booking_status } from "@prisma/client";

export const VALID_TRANSITIONS: Record<booking_status, booking_status[]> = {
  DRAFT: ["SEARCHING", "PENDING", "CANCELLED"],
  SEARCHING: ["VENDORS_NOTIFIED", "CANCELLED", "CONFIRMED"],
  PENDING: ["VENDORS_NOTIFIED", "CANCELLED", "REJECTED", "CONFIRMED"],
  VENDORS_NOTIFIED: ["QUOTE_RECEIVED", "CANCELLED", "REJECTED"],
  QUOTE_RECEIVED: ["QUOTE_ACCEPTED", "NEGOTIATING", "CANCELLED", "REJECTED"],
  NEGOTIATING: ["QUOTE_RECEIVED", "QUOTE_ACCEPTED", "CANCELLED", "REJECTED"],
  QUOTE_ACCEPTED: ["PAYMENT_PENDING", "CANCELLED"],
  PAYMENT_PENDING: ["CONFIRMED", "CANCELLED"],
  CONFIRMED: ["PREPARATION", "VENDOR_ASSIGNED", "CANCELLED"],
  PREPARATION: ["VENDOR_TRAVELING", "CANCELLED"],
  VENDOR_ASSIGNED: ["PREPARATION", "VENDOR_TRAVELING", "CANCELLED"],
  VENDOR_TRAVELING: ["VENDOR_ARRIVED", "CANCELLED"],
  VENDOR_ARRIVED: ["OTP_VERIFICATION_PENDING", "CANCELLED"],
  OTP_VERIFICATION_PENDING: ["EVENT_STARTED", "CANCELLED"],
  EVENT_STARTED: ["EVENT_ONGOING", "CANCELLED"],
  EVENT_ONGOING: ["EVENT_COMPLETED", "CANCELLED"],
  EVENT_COMPLETED: ["CUSTOMER_CONFIRMED", "CANCELLED"],
  CUSTOMER_CONFIRMED: ["PAYMENT_RELEASED"],
  PAYMENT_RELEASED: ["CLOSED"],
  CLOSED: [],
  REJECTED: [],
  CANCELLED: [],
  DISPUTED: ["CONFIRMED", "CANCELLED", "CLOSED"],
  IN_PROGRESS: ["EVENT_COMPLETED", "CANCELLED", "EMERGENCY"],
  EMERGENCY: ["IN_PROGRESS", "CANCELLED", "CLOSED"]
};

export function isValidTransition(currentStatus: booking_status, nextStatus: booking_status): boolean {
  const allowed = VALID_TRANSITIONS[currentStatus];
  if (!allowed) return false;
  return allowed.includes(nextStatus);
}
