export const BOOKING_STATUS = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  NEGOTIATING: "NEGOTIATING",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
  VENDOR_ASSIGNED: "VENDOR_ASSIGNED",
  VENDOR_TRAVELING: "VENDOR_TRAVELING",
  VENDOR_ARRIVED: "VENDOR_ARRIVED",
  OTP_VERIFICATION_PENDING: "OTP_VERIFICATION_PENDING",
  EVENT_STARTED: "EVENT_STARTED",
  EVENT_ONGOING: "EVENT_ONGOING",
  EVENT_COMPLETED: "EVENT_COMPLETED",
} as const;

export const VENDOR_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SUSPENDED: "SUSPENDED",
} as const;

export const SUBSCRIPTION_STATUS = {
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
} as const;

export const PAYMENT_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
} as const;
